[JENKINS-61136] Allows URL as input for readJSON
jenkinsci/pipeline-utility-steps-plugin pull request #73
Opened 2020-02-18 22:10 UTC by eXpire163

readJSON also allows now to read from an URL

2020-02-21 14:21 UTC, rsandell commented on src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStepExecution.java
> +		if (!isBlank(step.getUrl())){
Extra indentation

2020-02-21 14:21 UTC, rsandell commented on src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStepExecution.java
> +        connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0");
This looks hacky

2020-02-21 14:22 UTC, rsandell commented on src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStep/help-url.html
> +  ~ Copyright (c) 2016 Nikolas Falco, Christian Wiedemann
??

2022-11-15 18:03 UTC, jglick requested changes
Would be a serious security vulnerability. Do not merge.

2022-11-18 15:27 UTC, closed without merging